version: "3.8"

services:
  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: nextpox-backend
    environment:
      - PYTHONUNBUFFERED=1
      - UPLOAD_DIR=/app/uploads
      - CUDA_VISIBLE_DEVICES=-1
      - TF_CPP_MIN_LOG_LEVEL=2
    volumes:
      - ./uploads:/app/uploads
      - ./models:/app/models
    ports:
      - "7135:7135"
    depends_on:
      - mysql
    restart: unless-stopped
    networks:
      - proxy-net

  frontend:
    build:
      context: ./poxapp
      dockerfile: Dockerfile.deploy
    environment:
      - NODE_ENV=production
      - DATABASE_URL=mysql://dux:dux123@mysql:3306/skinconditions   # <-- use app user
      - PORT=7134
      - UPLOAD_DIR=/app/uploads
      # - OPENAI_KEY=${OPENAI_KEY}   # (optional) if your app needs it
    depends_on:
      - mysql
    volumes:
      - ./uploads:/app/uploads
    ports:
      - "7134:7134"
    # run migrations (or use `db push` if you don't have migrations yet)
    command: ["sh", "-c", "npx prisma migrate deploy || npx prisma db push; npm run build && npm run start -- -p 7134 -H 0.0.0.0"]
    restart: unless-stopped
    networks:
      - proxy-net

  mysql:
    image: mysql:8.0
    container_name: nextpox-mysql
    environment:
      MYSQL_ROOT_PASSWORD: fadifadi2025
      MYSQL_DATABASE: skinconditions
      MYSQL_USER: dux
      MYSQL_PASSWORD: dux123
    ports:
      - "7136:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - proxy-net

volumes:
  mysql-data:

networks:
  proxy-net:
    external: true