name: Build and Deploy (monkeypox)

on:
  push:
    branches:
      - monkeypox
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  BACKEND_IMAGE_NAME: nextpox-backend
  FRONTEND_IMAGE_NAME: nextpox-frontend

jobs:
  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}

      - name: Backend image metadata
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.BACKEND_IMAGE_NAME }}
          tags: |
            type=raw,value=monkeypox
            type=ref,event=branch
            type=sha

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}

      - name: Frontend image metadata
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ env.FRONTEND_IMAGE_NAME }}
          tags: |
            type=raw,value=monkeypox
            type=ref,event=branch
            type=sha

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./poxapp
          file: ./poxapp/Dockerfile.deploy
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}

  deploy:
    name: Deploy (Tailscale SSH)
    needs: build-and-push
    if: github.ref == 'refs/heads/monkeypox'
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TAILSCALE_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TAILSCALE_OAUTH_CLIENT_SECRET }}
          hostname: med-scribe-ci
          tags: tag:ci

      - name: Pull latest image on server
        env:
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
        run: |
          if [ -z "$DEPLOY_HOST" ]; then
              echo "DEPLOY_HOST secret must be set." >&2
              exit 1
          fi
          TARGET=${DEPLOY_HOST}
          if [ -n "$DEPLOY_USER" ]; then
              TARGET="${DEPLOY_USER}@${DEPLOY_HOST}"
          fi
          tailscale ssh "$TARGET" <<'REMOTE_CMD'
          set -euo pipefail
          cd mpox
          docker compose pull
          docker compose down
          docker compose up -d
          docker restart nginx-gateway
          REMOTE_CMD
